name = "gxyz"
version = "0.6.1"

description = "🛒 A small library of helper functions, that works as a companion of gleam_stdlib"
licences = ["MIT"]
repository = { type = "github", user = "bwireman", repo = "gxyz" }

[javascript]
typescript_declarations = true
runtime = "nodejs"

[javascript.deno]
allow_all = true

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleave = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
testament = ">= 0.1.0 and < 1.0.0"
