name = "gxyz"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "simple helper functions to compliment gleam_stdlib"
licences = ["MIT"]
repository = { type = "github", user = "bwireman", repo = "gxyz" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[javascript]
typescript_declarations = false
runtime = "nodejs"

[javascript.deno]
allow_all = true

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
