name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  otp: "28.0"
  gleam: "1.12.0"
  rebar: "3"
  nodelts: 22.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - run: gleam format --check src test

  erlang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - run: gleam test --target erlang

  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn install
      - run: gleam test --target javascript --runtime nodejs

  bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: gleam test --target javascript --runtime bun

  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.
      - run: deno install
      - run: gleam test --target javascript --runtime deno
